
# POST  http://localhost:3001/usersystem/register
# Content-Type: application/json

# {
#     "firstname": "Horned",
#     "lastname": "Owl",
#     "email": "hornedowl@gmail.com",
#     "phone": "0707459929",
#     "role": "admin",
#     "password": "password"
# }

POST  http://localhost:3001/usersystem/auth/login
Content-Type: application/json

{
    "email": "hornedowl@gmail.com",
    "password": "hornedOwl"
}

# POST  http://localhost:3001/usersystem/auth/resetPassword
# Content-Type: application/json

# {
#     "email": "hornedowl@gmail.com",
#     "password": "hornedOwl"
# }

