
POST  http://localhost:3001/usersystem/user/registerUser
Content-Type: application/json

{
    "firstname": "Horned",
    "lastname": "Owl",
    "email": "hornedowl@gmail.com",
    "phone": "0712345678",
    "role": "admin",
    "password": "hornedOwl24!"
}

# POST  http://localhost:3001/usersystem/auth/resetPassword
# Content-Type: application/json

# {
#     "email": "hornedOwl@gmail.com",
#     "password": "hornedOwl24!"
# }

# POST  http://localhost:3001/usersystem/auth/resetPassword
# Content-Type: application/json

# {
#     "email": "hornedowl@gmail.com",
#     "password": "hornedOwl"
# }

# POST  http://localhost:3001/usersystem/user/showUsers
# Content-Type: application/json


# POST  http://localhost:3001/usersystem/user/showUser
# Content-Type: application/json

# {
#     "user_id": 1013
# }

# POST  http://localhost:3001/usersystem/user/deleteUser
# Content-Type: application/json

# {
#     "user_id": 1014
# }


