# POST http://localhost:3001/usersystem/auth/login
# Content-Type: application/json

# {
#     "email": "hornedOwl@gmail.com",
#     "password": "hornedOwl24!"
# }

# normal user logged in
# {
#     "email": "azurestudio@gmail.com",
#     "password": "azureStudio24!"
# }



# POST http://localhost:3002/usersystem/projects/createProject
# Content-Type: application/json
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjp7InVzZXJfaWQiOjEzLCJmaXJzdG5hbWUiOiJIb3JuZWQiLCJsYXN0bmFtZSI6Ik93bCIsImVtYWlsIjoiaG9ybmVkb3dsQGdtYWlsLmNvbSIsInBob25lIjoiMDcwNzQ1OTkyOSIsInJvbGUiOiJhZG1pbiIsInByb2plY3RfaWQiOm51bGx9LCJpYXQiOjE2MzkzMzAxMTIsImV4cCI6MTYzOTMzMzcxMn0.yZKaejnQYXuRrYd7gdAwmF3pDp1bcSv6nvyF3uA27o0
 
#  {
#      "project_name": "Android application"
#  }

#  GET http://localhost:3002/usersystem/projects/showProjects
#  Content-Type: application/json
#  Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjp7InVzZXJfaWQiOjEzLCJmaXJzdG5hbWUiOiJIb3JuZWQiLCJsYXN0bmFtZSI6Ik93bCIsImVtYWlsIjoiaG9ybmVkb3dsQGdtYWlsLmNvbSIsInBob25lIjoiMDcwNzQ1OTkyOSIsInJvbGUiOiJhZG1pbiIsInByb2plY3RfaWQiOm51bGx9LCJpYXQiOjE2Mzk5ODIyNTEsImV4cCI6MTYzOTk4NTg1MX0.Hct3AcM7PG2qFqFrX4kSKCjrOAXgm9qFesJ6zT5gJEw

#  POST http://localhost:3002/usersystem/projects/deleteProject
#  Content-Type: application/json
#  Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjp7InVzZXJfaWQiOjEzLCJmaXJzdG5hbWUiOiJIb3JuZWQiLCJsYXN0bmFtZSI6Ik93bCIsImVtYWlsIjoiaG9ybmVkb3dsQGdtYWlsLmNvbSIsInBob25lIjoiMDcwNzQ1OTkyOSIsInJvbGUiOiJhZG1pbiIsInByb2plY3RfaWQiOm51bGx9LCJpYXQiOjE2MzkyMjMyODgsImV4cCI6MTYzOTIyNjg4OH0.ZLxJieOcnsJFMD5BipI59eJuVWPJ5VZqo28u8pqTnec

#  {
#      "project_id": 8
#  }

# POST http://localhost:3002/usersystem/projects/showProject
#  Content-Type: application/json
#  Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjp7InVzZXJfaWQiOjEzLCJmaXJzdG5hbWUiOiJIb3JuZWQiLCJsYXN0bmFtZSI6Ik93bCIsImVtYWlsIjoiaG9ybmVkb3dsQGdtYWlsLmNvbSIsInBob25lIjoiMDcwNzQ1OTkyOSIsInJvbGUiOiJhZG1pbiIsInByb2plY3RfaWQiOm51bGx9LCJpYXQiOjE2MzkyMjMyODgsImV4cCI6MTYzOTIyNjg4OH0.ZLxJieOcnsJFMD5BipI59eJuVWPJ5VZqo28u8pqTnec

#  {
#      "project_id": 34
#  }

# POST http://localhost:3002/usersystem/projects/showTasksInProject
# Content-Type: application/json
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjp7InVzZXJfaWQiOjEzLCJmaXJzdG5hbWUiOiJIb3JuZWQiLCJsYXN0bmFtZSI6Ik93bCIsImVtYWlsIjoiaG9ybmVkb3dsQGdtYWlsLmNvbSIsInBob25lIjoiMDcwNzQ1OTkyOSIsInJvbGUiOiJhZG1pbiIsInByb2plY3RfaWQiOm51bGx9LCJpYXQiOjE2MzkzMzAxMTIsImV4cCI6MTYzOTMzMzcxMn0.yZKaejnQYXuRrYd7gdAwmF3pDp1bcSv6nvyF3uA27o0

#  {
#      "project_id": 4
#  }

#  POST http://localhost:3002/usersystem/projects/assignProject
#  Content-Type: application/json
#  Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjp7InVzZXJfaWQiOjEzLCJmaXJzdG5hbWUiOiJIb3JuZWQiLCJsYXN0bmFtZSI6Ik93bCIsImVtYWlsIjoiaG9ybmVkb3dsQGdtYWlsLmNvbSIsInBob25lIjoiMDcwNzQ1OTkyOSIsInJvbGUiOiJhZG1pbiIsInByb2plY3RfaWQiOm51bGx9LCJpYXQiOjE2MzkyMjMyODgsImV4cCI6MTYzOTIyNjg4OH0.ZLxJieOcnsJFMD5BipI59eJuVWPJ5VZqo28u8pqTnec

#  {
#      "user_id": 1022,
#      "project_id": 8
#  }
# POST http://localhost:3002/usersystem/tasks/createTask
# Content-Type: application/json
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjp7InVzZXJfaWQiOjEzLCJmaXJzdG5hbWUiOiJIb3JuZWQiLCJsYXN0bmFtZSI6Ik93bCIsImVtYWlsIjoiaG9ybmVkb3dsQGdtYWlsLmNvbSIsInBob25lIjoiMDcwNzQ1OTkyOSIsInJvbGUiOiJhZG1pbiIsInByb2plY3RfaWQiOm51bGx9LCJpYXQiOjE2MzkzMzAxMTIsImV4cCI6MTYzOTMzMzcxMn0.yZKaejnQYXuRrYd7gdAwmF3pDp1bcSv6nvyF3uA27o0

# {
#     "task_name": "Volley Multipart Request",
#     "task_description": "Create a volley class to upload multipart data"
# }

# POST http://localhost:3002/usersystem/tasks/deleteTask
# Content-Type: application/json
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjp7InVzZXJfaWQiOjEzLCJmaXJzdG5hbWUiOiJIb3JuZWQiLCJsYXN0bmFtZSI6Ik93bCIsImVtYWlsIjoiaG9ybmVkb3dsQGdtYWlsLmNvbSIsInBob25lIjoiMDcwNzQ1OTkyOSIsInJvbGUiOiJhZG1pbiIsInByb2plY3RfaWQiOm51bGx9LCJpYXQiOjE2MzkzMzAxMTIsImV4cCI6MTYzOTMzMzcxMn0.yZKaejnQYXuRrYd7gdAwmF3pDp1bcSv6nvyF3uA27o0

# {
#     "task_id": 10
# }

GET http://localhost:3002/usersystem/tasks/showTasks
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjp7InVzZXJfaWQiOjEzLCJmaXJzdG5hbWUiOiJIb3JuZWQiLCJsYXN0bmFtZSI6Ik93bCIsImVtYWlsIjoiaG9ybmVkb3dsQGdtYWlsLmNvbSIsInBob25lIjoiMDcwNzQ1OTkyOSIsInJvbGUiOiJhZG1pbiIsInByb2plY3RfaWQiOm51bGx9LCJpYXQiOjE2Mzk5ODQwODksImV4cCI6MTYzOTk4NzY4OX0.-cKJUHNaFGHreGox1_2uLtvRJpEonfvR0bUPcQg3ZIw

# POST http://localhost:3002/usersystem/tasks/showTask
# Content-Type: application/json
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjp7InVzZXJfaWQiOjEzLCJmaXJzdG5hbWUiOiJIb3JuZWQiLCJsYXN0bmFtZSI6Ik93bCIsImVtYWlsIjoiaG9ybmVkb3dsQGdtYWlsLmNvbSIsInBob25lIjoiMDcwNzQ1OTkyOSIsInJvbGUiOiJhZG1pbiIsInByb2plY3RfaWQiOm51bGx9LCJpYXQiOjE2MzkzMzc4ODQsImV4cCI6MTYzOTM0MTQ4NH0.bkTPrZD7x1o2iyumE2MApytsx04GdQHOyVPUIvW8vFw

# {
#     "task_id": 10
# }

# POST http://localhost:3002/usersystem/tasks/assignTask
# Content-Type: application/json
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjp7InVzZXJfaWQiOjEzLCJmaXJzdG5hbWUiOiJIb3JuZWQiLCJsYXN0bmFtZSI6Ik93bCIsImVtYWlsIjoiaG9ybmVkb3dsQGdtYWlsLmNvbSIsInBob25lIjoiMDcwNzQ1OTkyOSIsInJvbGUiOiJhZG1pbiIsInByb2plY3RfaWQiOm51bGx9LCJpYXQiOjE2MzkzMzc4ODQsImV4cCI6MTYzOTM0MTQ4NH0.bkTPrZD7x1o2iyumE2MApytsx04GdQHOyVPUIvW8vFw

# {
#     "user_id": 1022,
#     "task_id": 10,
#     "project_id": 9
# }

